// lib/narrative/ending-catalog.ts
//
// Curated atmospheric inspiration for the motif diversity pass.
// Each atmosphere is a small set of quiet, sensory closing images that
// a rewriter can lean on when an ending beat already echoes something
// earlier in the story. These are inspirations, NOT templates — the
// prompt in motif-diversity.ts explicitly tells the model to use them
// only as local substitutions, never as forced endings.
//
// German is the primary catalog. English entries are kept for the
// rare case the narrative pipeline runs in English. Both lists share
// the same EndingAtmosphere keys so callers can switch by output
// language without changing structure.
//
// To extend: add or refine entries inside an existing atmosphere, or
// add a new atmosphere by extending the EndingAtmosphere union and
// providing arrays in BOTH catalogs (DE first).

export type EndingAtmosphere =
  | "coastal_maritime"
  | "alpine_village"
  | "autumn"
  | "winter"
  | "house_interior"
  | "train_journey"
  | "family_home"
  | "forest"
  | "rainy_evening"
  | "fireplace"
  | "harbor"
  | "summer_countryside";

export const ENDING_MOTIF_CATALOG_DE: Record<EndingAtmosphere, string[]> = {
  coastal_maritime: [
    "ein leises Nebelhorn weit draußen vor der Hafenmauer",
    "das langsame Wiegen eines Bootes am hölzernen Steg",
    "Salz in der Luft, das von den Steinen heraufzieht",
    "eine einzelne Möwe, die sich auf einem nassen Poller niederlässt",
    "die lange Linie der ablaufenden Flut unter grauem Licht",
    "der Geruch von Seetang an der Buhne",
    "ein schmaler Sandstreifen, schon dunkel von der Welle",
    "Tau auf dem Geländer der Mole",
    "ein Fischerboot mit erloschener Lampe",
    "die Stille zwischen zwei kleinen Wellen",
    "ein Schiff, das langsam aus der Bucht zieht",
    "die Wärme einer Hand am kalten Geländer",
  ],
  alpine_village: [
    "Lampenlicht in einem hohen Fenster über einer ruhigen Gasse",
    "das leise Knarren von Holz, das sich in der Dämmerung setzt",
    "Schnee, der sich auf einem Schieferdach sammelt",
    "eine Kirchenglocke, die die kalte Luft hält",
    "Fußspuren, die auf dem Heimweg schon weicher werden",
    "der Atem, der sich vor der Tür kurz zur Wolke macht",
    "ein Bündel Holz an der Hauswand",
    "das gedämpfte Rauschen eines Bachs unter der Brücke",
    "ein Stall, in dem das Licht schon brennt",
    "die Berge, die weiter weg wirken als am Morgen",
    "ein Geländer, das auch von oben her einlädt",
    "ein Tor, das jemand vorsichtig schließt",
  ],
  autumn: [
    "Blätter, die sich langsam in einem Hoflicht bewegen",
    "der Geruch von Holzrauch aus dem Schornstein eines Nachbarn",
    "ein tiefer Sonnenstrahl an einer Küchenwand",
    "ein brauner Apfel, der auf der Fensterbank liegt",
    "das Jahr, das sich in einem einzigen Atemzug wendet",
    "Kastanien in einer Schale neben der Tür",
    "der erste Nebel über dem Garten",
    "feuchte Erde unter dem Kastanienbaum",
    "eine Tasse Tee, die in der Küche kühl wird",
    "ein Pullover, der über einem Stuhl hängt",
    "das Knistern von Laub auf einem Steinweg",
    "Spinnweben im Licht des frühen Abends",
  ],
  winter: [
    "Schneefall, der sich hinter einem halb zugezogenen Vorhang verdichtet",
    "der Kessel, der sich auf der Herdplatte beruhigt",
    "Eis, das auf einer Stufe vor dem Haus fester wird",
    "ein einzelnes Heizungsrohr, das in einem ruhigen Raum tickt",
    "der Raum, der wärmer wird als das Dunkel dahinter",
    "Frost auf dem Innenrahmen eines Fensters",
    "ein Paar Schuhe, das in der Diele auftaut",
    "die Stille, die sich nur der Schnee leisten kann",
    "der erste Stern über einem Schneefeld",
    "eine Tür, die sich gegen den Wind hält",
    "ein Hund, der sich nahe am Ofen einrollt",
    "Atem, der vor einem dunklen Fenster für einen Moment sichtbar wird",
  ],
  house_interior: [
    "eine Lampe, die im Flur eingeschaltet bleibt",
    "die Uhr im Nebenraum, die einmal schlägt",
    "ein Stuhl, der wieder an seinen Platz am Tisch geschoben wird",
    "eine zusammengelegte Decke auf der Armlehne des Sofas",
    "das kleine Geräusch einer Tür, die leise zugezogen wird",
    "Wasser, das in einer Karaffe ruht",
    "die warme Linie eines Ofens an einer Wand",
    "ein paar offene Bücher auf einem niedrigen Tisch",
    "der Schatten eines Vorhangs, der sich kaum bewegt",
    "ein Schlüsselbund, der lautlos am Haken hängt",
    "ein Teller, der trocknend neben dem Becken steht",
    "ein letzter Ton aus einem Radio, ehe es leise wird",
  ],
  train_journey: [
    "der Rhythmus der Schienen, der in einer langen Kurve nachlässt",
    "die Lichter einer kleinen Station, die vorüberziehen, ohne zu halten",
    "Regen, der in schrägen Linien das Fenster quert",
    "ein Mantel, der auf dem Sitz daneben gefaltet liegt",
    "der Wagen, der mit fortschreitender Stunde stiller wird",
    "ein Gepäckstück, das sich in der Ablage leicht bewegt",
    "das gleichmäßige Sirren der Heizung unter dem Sitz",
    "ein Schaffner, der ohne Worte vorbeigeht",
    "ein Buch, das auf einer Seite liegen bleibt",
    "der Geruch von Kaffee aus einem fernen Wagen",
    "ein Bahnhof, der schon halb im Dunkel liegt",
    "ein Spiegelbild im Fenster, das ruhig zurückblickt",
  ],
  family_home: [
    "ein Küchenlicht, das brennt, nachdem alle schon im Bett sind",
    "die Zeichnung eines Kindes, mit Klebeband an der Kühlschranktür",
    "zwei Tassen, die nebeneinander auf der Anrichte stehen",
    "eine Hand, die kurz auf dem Geländer am oberen Treppenabsatz ruht",
    "das Haus, das sich um seine Menschen legt",
    "ein offenes Kinderzimmer, in dem nur ein Nachtlicht leuchtet",
    "der gefaltete Stapel sauberer Wäsche auf dem Esstisch",
    "ein Foto, das an einer Pinnwand fast vergessen hängt",
    "ein Spielzeug, das auf einer Treppenstufe liegen geblieben ist",
    "der Klang von Hausschuhen, die durch den Flur kommen",
    "ein Hund, der sich vor der Schlafzimmertür niederlegt",
    "ein Tee, der für später in einer Kanne wartet",
  ],
  forest: [
    "das Knirschen von Nadeln unter ruhigen Schritten",
    "ein Lichtkegel zwischen zwei Tannenstämmen",
    "der Geruch von feuchtem Holz und kühler Erde",
    "ein Vogel, der weit oben einen einzelnen Ton ruft",
    "Moos, das eine alte Wurzel überzieht",
    "Nebelschwaden, die sich zwischen Stämmen verlieren",
    "das leise Tropfen, das nicht mehr Regen ist",
    "ein Stein am Wegrand, der sich warm anfühlt",
    "ein Pfad, der hinter einem niedrigen Hang verschwindet",
    "die Stille zwischen zwei Schritten",
    "das gedämpfte Rauschen ferner Wipfel",
    "ein Reh, das ohne Eile zur Seite tritt",
  ],
  rainy_evening: [
    "Regen, der in schmalen Linien an der Scheibe entlangzieht",
    "das Geräusch der Tropfen auf einem alten Blechdach",
    "ein einzelnes Auto, das vorsichtig durch eine Pfütze fährt",
    "der Glanz nasser Pflastersteine unter einer Straßenlaterne",
    "ein offener Schirm, der in einem Hauseingang trocknet",
    "die wärmere Luft eines Cafés hinter beschlagenem Fenster",
    "Kerzenlicht, das sich in einer regennassen Scheibe sammelt",
    "eine Mantelfalte, die langsam dunkler wird vom Regen",
    "das Tröpfeln einer Dachrinne in einen Hof",
    "der Geruch von feuchtem Stein und Stadt",
    "ein Buch in einem trockenen Schoß, ehe der Tag endet",
    "ein Hund, der sich gemächlich unter einen Vorsprung legt",
  ],
  fireplace: [
    "die ruhige Glut, die im Kamin nachatmet",
    "ein Holzscheit, das sich leise in sich selbst setzt",
    "der Schimmer des Feuers auf einer alten Tischplatte",
    "der Geruch von Rauch, der ganz im Raum bleibt",
    "ein Sessel, der nah an die Wärme gerückt ist",
    "ein Streichholz, das auf einem Stein verbrannt zur Ruhe kommt",
    "die Wärme, die einem aus dem Stoff der Decke entgegenkommt",
    "ein Schatten, der an der Wand langsam größer wird",
    "ein Topf, der oben auf dem Ofen leise summt",
    "ein Buch, das geöffnet im Schoß liegt",
    "die letzte Funke vor dem langen Ausatmen der Kohle",
    "ein Kissen, das schon die Form eines Schlafenden hat",
  ],
  harbor: [
    "das hohle Knarren von Pollern, an denen sich die Leinen bewegen",
    "Möwen, die in weiten Bögen vorüberziehen",
    "das Patschen kleiner Wellen gegen einen Bootsrumpf",
    "eine Kette, die langsam ausgelegt wird",
    "ein Leuchtturm, der seine Linie über die Wasserfläche legt",
    "der Geruch von Seetang und Diesel an einer Mole",
    "ein Fischerboot, das langsam an seinen Liegeplatz zurückkehrt",
    "ein Tau, das nass auf der Planke liegt",
    "die langsame Hebung einer Brücke ohne Eile",
    "ein Kran, der für die Nacht ruht",
    "eine Lampe an einem hohen Pfahl, die den Wassersaum erfasst",
    "die Stille, die zwischen zwei Tankern liegt",
  ],
  summer_countryside: [
    "das ferne Klingeln eines Glöckchens an einer Kuh",
    "ein langes Feld, in dem der Wind eine Welle zieht",
    "der Geruch von gemähtem Gras nach einem langen Tag",
    "ein Heuschober, der sich in einem ruhigen Hof setzt",
    "ein Bach, der unter einer Holzbrücke ruhig wird",
    "ein Insektenflug, der die letzte Sonne durchquert",
    "ein Hof, dessen Türen am Abend offenstehen",
    "ein Baum, dessen Schatten sich auf einer Bank ausstreckt",
    "ein Dorflicht, das hinter einem Hügel aufgeht",
    "das Tropfen einer Pumpe in einen Steintrog",
    "der Atem warmer Steine, die den Tag noch halten",
    "ein Weg, der zwischen Hecken zur Tür zurückführt",
  ],
};

export const ENDING_MOTIF_CATALOG_EN: Record<EndingAtmosphere, string[]> = {
  coastal_maritime: [
    "a low foghorn far out past the harbour",
    "the slow rocking of a boat against a wooden pier",
    "salt in the air carried up from the rocks",
    "a single gull settling on a wet bollard",
    "the long line of a tide receding under grey light",
    "the smell of seaweed along the groyne",
    "a narrow strip of sand already dark from a wave",
    "dew on the railing of the mole",
    "a fishing boat with its lamp gone out",
    "the silence between two small waves",
  ],
  alpine_village: [
    "lamplight in a high window above a quiet street",
    "the soft creak of timber settling at dusk",
    "snow gathering on a slate roof",
    "a church bell catching the cold air",
    "footprints already softening on the path home",
    "a bundle of wood against the wall of a house",
    "the muffled rush of a stream under the bridge",
    "a stable already lit for the evening",
    "the mountains looking further off than they did at morning",
    "a gate someone closes with care",
  ],
  autumn: [
    "leaves moving slowly in a yard light",
    "the smell of wood smoke from a neighbour's chimney",
    "a low sun on a kitchen wall",
    "a brown apple left on the sill",
    "the year turning in a single careful breath",
    "chestnuts in a bowl by the door",
    "the first fog over the garden",
    "damp earth under the chestnut tree",
    "a sweater hung over the back of a chair",
    "spider-silk in the light of an early evening",
  ],
  winter: [
    "snowfall thickening past a half-drawn curtain",
    "the kettle settling on the hob",
    "ice tightening on a step outside",
    "a single radiator ticking in a still room",
    "the room growing warmer than the dark beyond it",
    "frost on the inner frame of a window",
    "a pair of shoes thawing in the hallway",
    "the silence only snow can afford",
    "the first star above an open field of snow",
    "a dog curling itself close to the stove",
  ],
  house_interior: [
    "a lamp left on in the hallway",
    "the clock in the next room ticking once",
    "a chair pulled back to its place at the table",
    "a folded blanket on the arm of the sofa",
    "the small sound of a door easing closed",
    "water resting in a carafe",
    "the warm line of a stove along a wall",
    "a few open books on a low table",
    "the shadow of a curtain barely moving",
    "a key ring hanging silent on its hook",
  ],
  train_journey: [
    "the rhythm of the rails easing into a long curve",
    "lights of a small station passing without stopping",
    "rain crossing the window in slow diagonals",
    "a coat folded on the next seat",
    "the carriage growing quieter as the hour deepens",
    "a piece of luggage shifting gently on the rack",
    "the even hum of heating beneath the seat",
    "a conductor passing without a word",
    "a book left open to a single page",
    "the smell of coffee from a distant carriage",
  ],
  family_home: [
    "a kitchen light left on after everyone has gone to bed",
    "a child's drawing taped to the fridge in the half-dark",
    "two cups left side by side on the counter",
    "a hand resting briefly on a banister at the top of the stairs",
    "the house settling around its people",
    "a quiet child's room lit only by a night light",
    "a folded stack of clean laundry on the dining table",
    "a photograph almost forgotten on a pinboard",
    "a toy left behind on a step of the stairs",
    "the sound of slippers coming through the hall",
  ],
  forest: [
    "the crunch of needles under quiet steps",
    "a cone of light between two pine trunks",
    "the smell of damp wood and cool earth",
    "a bird calling a single note from high up",
    "moss covering an old root",
    "mist drifting between trunks and losing itself",
    "the soft dripping that is no longer rain",
    "a stone by the path that feels warm",
    "a path disappearing behind a low rise",
    "the hush between two footfalls",
  ],
  rainy_evening: [
    "rain drawing thin lines along the pane",
    "the sound of drops on an old tin roof",
    "a single car easing through a puddle",
    "the gleam of wet cobblestones under a streetlamp",
    "an open umbrella drying in a doorway",
    "the warmer air of a café behind fogged glass",
    "candlelight gathered in a rain-wet pane",
    "the fold of a coat slowly darkening with rain",
    "the drip of a gutter into a small yard",
    "a book in a dry lap before the day ends",
  ],
  fireplace: [
    "the quiet glow still breathing in the hearth",
    "a log settling softly into itself",
    "firelight on an old tabletop",
    "the smell of smoke held entirely in the room",
    "an armchair drawn close to the warmth",
    "a matchstick burnt out on a hearthstone",
    "warmth reaching out of the fabric of a blanket",
    "a shadow growing slowly along the wall",
    "a pot humming softly atop the stove",
    "a book lying open in a lap",
  ],
  harbor: [
    "the hollow creak of bollards as lines shift",
    "gulls turning in wide arcs above the water",
    "the slap of small waves against a hull",
    "a chain being laid out without hurry",
    "a lighthouse drawing its line across the water",
    "the smell of seaweed and diesel along the mole",
    "a fishing boat returning slowly to its berth",
    "a rope lying wet on the planking",
    "a crane resting for the night",
    "a lamp on a high pile catching the waterline",
  ],
  summer_countryside: [
    "the far ring of a small bell on a cow",
    "a long field where the wind draws a single wave",
    "the smell of cut grass after a long day",
    "a haystack settling in a quiet yard",
    "a stream growing calm beneath a wooden bridge",
    "an insect's flight crossing the last of the sun",
    "a farm whose doors stand open into the evening",
    "a tree whose shadow stretches across a bench",
    "a village light rising behind a low hill",
    "the breath of warm stones still holding the day",
  ],
};

export function getEndingCatalog(
  language: "English" | "German",
): Record<EndingAtmosphere, string[]> {
  return language === "English" ? ENDING_MOTIF_CATALOG_EN : ENDING_MOTIF_CATALOG_DE;
}
